export const LocalizedStrings = {
  "en": {
    patients: "Patients",
    PATIENTS: "< PATIENTS",
    welcome: "Welcome Back",
    dob: "Date of Birth",
    DOB: "DOB",
    sex: "Sex",
    gender: "Gender",
    GENDER: "GENDER",
    patientSummary: "Patient Summary",
    noContent: "No content yet",
    age: "AGE",
    edit: "EDIT",
    back: "< BACK",
    save: "SAVE",
    confirm: "CONFIRM",
    cancel: "CANCEL",
    yes: "Yes",
    no: "No",
    firstName: "First Name",
    surname: "Last name",
    country: "Country",
    hometown: "Hometown",
    selectDob: "Select DOB",
    phone: "Phone",
    patientSearch: "Search patient name...",
    search: "Search",
    minAge: "Min Age",
    maxAge: "Max Age",
    advancedFilters: "Advanced Filters ▼",
    hideFilters: "Hide Filters",
    clearFilters: "Clear All Filters",
    newPatient: "New Patient",
    newVisit: "New Visit",
    newEntry: "New Entry",
    camp: "Address",
    vitals: "Vitals",
    examination: "Examination",
    notes: "Notes",
    complaint: "Chief complaint",
    treatment: "Treatment",
    diagnosis: "Diagnosis",
    medicineDispensed: "Medicine Dispensed",
    prescriptions: "Prescriptions",
    allergies: "Allergies",
    medicalHistory: "Medical History",
    covidScreening: "COVID-19 Screening",
    enterTextHere: "Enter text here.",
    visitDate: "Visit Date",
    visitHistory: "Visit History",
    visitEvents: "Visit Events",
    visitType: "Visit Type",
    trends: "TRENDS",
    eventType: "Event Type",
    datePrescribed: "Date Prescibed",
    provider: "Provider",
    severity: "Severity",
    onsetDate: "Onset Date",
    departure: "Departure",
    to: "to",
    return: "Return",
    fever: "Fever or Chills?",
    dryCough: "Dry Cough?",
    diffBreathing: "Difficulty Breathing?",
    soreThroat: "Sore Throat or Runny Nose?",
    nausea: "Nausea, vomiting, or diarrhea?",
    chestPain: "Chest Pain?",
    confusion: "New Confusion?",
    bluish: "Bluish Lips or Face?",
    fatigue: "Fatigue?",
    aches: "Aches and Pains?",
    headache: "Headache?",
    changeTasteSmell: "Change of Taste or Smell?",
    diabetes: "Diabetes?",
    cardioDisease: "Cardiovascular Disease?",
    pulmonaryDisease: "Pulmonary Disease?",
    renalDisease: "Renal Disease?",
    malignancy: "Malignancy?",
    pregnant: "Pregnant or 2 weeks postpartum?",
    immunocompromised: "Immunocompromised?",
    exposureKnown: "Recent contact with individuals with known or suspected COVID-19?",
    travel: "Recent travel out of the country?",
    symptomsDate: "Onset Date of first symptoms?",
    riskFactors: "Risk Factors",
    hideRiskFactors: "Hide Risk Factors",
    testIsolate: "Test/Isolate Patient",
    seekCare: "Seek Emergency Care and Isolate",
    noAction: "No Action Necessary",
    syncFailure: "Database Sync Failure!",
    syncFailureConnection: "Check internet connection",
    syncFailureSystem: "Contact system administrator",
    syncSuccess: "Database Sync Success",
    surgeryHx: "Previous Surgeries",
    chronicConditions: "Chronic Conditions",
    currentMedications: "Current Medications",
    vaccinations: "Vaccinations",
    generalObservations: "General Observations",
    covid19: "COVID-19",
    referral: "Referral to Specialist",
    medicine: "Medicine",
    medication: "Medication",
    type: "Type",
    tablet: "Tablet",
    syrup: "Syrup",
    ampule: "Ampule",
    suppository: "Suppository",
    cream: "Cream",
    drops: "Drops",
    bottle: "Bottle",
    spray: "Spray",
    gel: "Gel",
    lotion: "Lotion",
    dosage: "Dosage",
    days: "Days",
    dentalTreatment: "Dental Treatment",
    physiotherapy: "Physical Exam",
    previousTreatment: "Previous Physical Exam",
    findings: "Examination Findings",
    treatmentPlan: "Treatment Plan",
    treatmentSession: "Treatment Session",
    recommendations: "Recommendations",
    patientSnapshot: "Patient Snapshot",
    logOut: "Log Out",
    sync: "Sync",
    // Mexico Clinic
    traumaType: "Trauma type",
    traumaDesc: "(DO NOT ask about this; only check mark if they self-volunteered the information)",
    traumaPhysical: "Physical",
    traumaSexual: "Sexual",
    traumaAbuse: "Witnessed abuse",
    traumaKilling: "Witnessed killing",
    traumaPSeperation: "Parental separation",
    traumaThreats: "Threats",
    traumaTJ: "Abuse in TJ",
    traumaOthers: "Others",
    // Mexico - Common Problems
    commonProblems: "Mental Health Common Problems",
    commonProblemsDesc: 'If there is tiem, fill out the questionnaire on the second page and mark the items that are applicable. If there is no time, it is not necessary to evaluate all the questions below nor the ones on the second page. Simply start by asking: “With what problems or stress that you’re currently having would you like help with?',
    commonProblemsHint: "Items that you must definitely check. Include the frequency when it is possible (ex. 2x/week)",
    difficultyEating: "Difficulty Eating",
    suicidalIdeation: "Suicidal Ideation",
    difficultySleeping: "Difficulty sleeping",
    hoursSlept: "Hours Slept",
    sleepingNight: "Nightmares",
    sleepingFalling: "Falling Asleep",
    sleepingWalking: "Waking Up middle of night",
    childrenSpecific: "Specific to Children",
    bedWetting: "Bed Wetting",
    defiant: "Defiant, fighting, or irritable",
    separationAnxiety: "Separation anxiety",
    communicationDifficulties: "Communication/learning difficulties",
    restless: "Restless",
    difficultyStoppingWorrying: "Difficulty stopping worrying",
    bodyAches: "Body Aches",
    bodyAchesWhere: "If so, where:",
    lowEnergy: "Low energy",
    noInterest: "No interest",
    guilt: "Guilt",
    hopeless: "Hopeless",
    flashbacks: "Flashbacks",
    hypervigilance: "Hypervigilance",
    sadIrritable: "Sad, cries often, or irritable",
    hallucinations: "Hallucinations (hears commands to kill/injure)",
    potentialDiagnosis: "Potential diagnosis",
    otherSymptom: "Other symptom/notes",
    // Interventions Used Form
    interventions: "Mental Health Interventions",
    resourceConnection: "Resource Connection",
    resourceConnectionSpecify: "Specify",
    activeListening: "Active Listening / Validation",
    psychoeducation: "Psychoeducation",
    sleepHygiene: "Sleep Hygiene",
    safeSpaceImagine: "Imagine a Safe Space",
    muscleRelaxation: "Progressive Muscle Relaxation",
    behavioralActivation: "Behavioral Activation",
    griefLetter: "Letter for Grief",
    changingThoughts: "Changing Thoughts",
    senses: "5 Senses",
    distractionTechniques: "Distraction Techniques",
    diaryYourself: "A Diary- praise yourself",
    chairTechnique: "Chair Technique",
    buildStrengths: "Build on Strengths/solutions",
    motivationalInterviewing: "Motivational Interviewing",
    diaphragmaticBreathing: "Diaphragmatic Breathing",
    safetyPlan: "Safety plan (note details; have migrant take picture of plan too)",
    interpersonalCommunication: "Interpersonal Communication",
    prayer: "Prayer (only if migrant self-reports already uses strategy)",
    supportivePeople: "Supportive people in their network",
    otherStrategies: "Other strategies used and safety/supervision plan details:",
    psychiatricMedications: "Psychiatric/Relevant Medications (Medicamentos):",
    // Mental Health
    mentalHealthFollowUp: "Mental health follow-up",
    inPerson: "In Person",
    tele: "Tele",
    femaleOnly: "Female Only",
    goClinic: "Go to Clinic",
    mentalOther: "Other",
    acupuncture: "Acupuncture (Wednesday and Thursday 9-1pm):",
    sendAudio: "Send Audios/Videos",
    psychiatry: "Psychiatry: First-time referral",
    refill: "Refill",
    takingRegularly: "Talking regularly",
    concernsFollowup: "Followup for concerns",
    lastFollowUpDate: "How long did the follow-up last:",
    firstSectionHint: "For people aged 12 or over, ask at the 1st session, 4th session and every 4 sessions after:",
    firstSectionQuestion: "Over the past 2 weeks, how often have you been bothered by the following problems:",
    notAtAll: "Not at all",
    severalDays: "Several days",
    moreHalfDays: "More than half the days",
    nearlyEveryDay: "Nearly every day",
    feelingNervous: "Feeling nervous, anxious, or on edge",
    noControlWorrying: "Not being able to stop or control worrying",
    littleInterest: "Little interest or pleasure in doing things",
    feelingDown: "Feeling down, depressed or hopeless",
    cantSleep: "I can't sleep or have nightmares",
    dontFeelSafeLiving: "I don't feel safe where I live (i.e., in my shelter or home; for people who live on the streets, you can ask if they know resources available to them)",
    firstSectionScore: "Total score (sum of four questions):",
    // Mental Section2
    secondSectionQuestion: "From the statements below, please mark or circle the answer that best describes how you feel. Do you feel that:",
    dealWithAny: "Is able to deal (cope) with anything",
    dealWithMostThings: "Is able to deal (cope) with most things ",
    dealWithSomeThings: "Is able to deal (cope) with some things, but cannot deal with other things",
    cannotDealWithMost: "Can't deal with most things",
    cannotDealWithAny: "Can't deal with anything",
    // Mental Section3
    thirdSectionHint: "For parents of children aged 11 or under, ask at the 1st session, 4th session and every 4 sessions after:",
    thridSectionQuestion: "How often did each of these happen in the last 30 days?",
    frequent1: "Never/Rarely",
    frequent2: "1-2 times per month",
    frequent3: "1-2 times per week",
    frequent4: "+3 times per week",
    childBodyFeeling: "Your child has strong feelings in their body when they remember something that happened (sweating, heart beats fast, feel sick).",
    childAwayFromPeople: "Your child tries to stay away from people, places, or things that remind them about something that happened.",
    childFeelingHappy: "Your child has trouble feeling happy.",
    childTroubleSleeping: "Your child has trouble sleeping.",
    childHardPayAttention: "It's hard for your child to concentrate or pay attention.",
    childFeelsAlone: "Your child feels alone and not close to people around them.",
    forthSectionHint: " For children aged 11 or under, ask at the 1st session, 4th session and every 4 sessions after:",
    forthSectionQuestion: "How often did each of these happen in the last 30 days?",
    bodyFeelings: "Strong feelings in your body when you remember something that happened (sweating, heart beats fast, feel sick).",
    awayFromPeople: "Try to stay away from people, places, or things that remind you about something that happened.",
    feelingHappy: "Trouble feeling happy.",
    troubleSleeping: "Trouble sleeping.",
    hardPayAttention: "Hard to concentrate or pay attention.",
    feelAlone: "Feel alone and not close to people around you.",
    pastWeekStress: "Circle the number (0-10) that describes how much stress you have been feeling this past week, including today:",
    none: "None",
    little: "A little",
    moderately: "Moderately",
    goodDeal: "A Good Deal",
    alot: "A lot (The Worse)",

    // Vitals
    respiratoryRate: "Respiratory Rate",
    bloodGlucose: "Blood Glucose",
    weight: "Weight",
    pulse: "Pulse",

    // Medicine
    route: "Route",
    oral: "Oral",
    topical: "Topical",
    subcutaneous: "Subcutaneous",
    intramuscular: "Intramuscular",
    deepIntramuscular: "Deep Intramuscular",

    // Physical Exam
    hpi: "HPI",
    examinationFindings: "Ros/Examination findings",
    appearance: "Appearance",
    eent: "EENT",
    heartPulses: "Heart, pulses",
    lungs: "Lungs",
    abdomen: "Abdomen",
    genitales: "Genitales",
    extremities: "Extremities",
    skin: "Skin",
    neuro: "Neuro",
    isPregnant: "Pregnant",
    lastPeriodFirstDay: "First day of last period?",
    assessmentPlan: "Assessment and Plan",
    unsure: "Unsure",

    // Medical History
    tobacco: "Tobacco",
    alcohol: "Alcohol",
    drugs: "Drugs",
    familyHistory: "Family History",
    diseasesConditions: "Diseases/Conditions",
    medicalHistoryDetails: "What relatives? dates? Treatment / Other?",
    cancer: "Cancer",
    epilepsy: "Epilepsy or other Seizures",
    heartDisease: "Heart Disease",
    hypertension: "Hypertension",
    thyroidConditions: "Thyroid Conditions",
    tuberculosis: "Tuberculosis",
    // diabetes: "Diabetes",
    multipleBirths: "Multiple Births (Twins)",
    breechBirths: "Breech Births",
    spiritualEmotionalHistory: "Spiritual Emotional History",
    spiritualEmotionalHistoryDetails: "What relatives (direct or distant)? dates? Treatment / Other?",
    conditions: "Conditions",
    domesticViolence: "Domestic Violence",
    alcoholismDrugAddiction: "Alcoholism / Drug Addiction",
    codependency: "Codependency",
    nutritionalDisorder: "Nutritional Disorder",
    abuse: "Abuse",
    sexualAbuse: "sexual abuse",
    mentalDisorders: "Mental disorders",
    showMore: "Show more medicines:",

    // Nursing notes
    nursingNotes: "Nursing Notes",
    bodyHabitus: "Body Habitus",
    procedures: "Procedures",
    observations: "Observations",

    // Lab
    bloodTestImaging: "Blood Test and Imaging",
    date: "Date",
    test: "Test",
    normal: "Normal",
    abnormal: "Abnormal",
    labNotes: "Notes",
    bloodTest: "Blood Test",
    imaging: "Imaging",
    typeOfImaging: "Type of imaging",
    result: "Result",

    // Gender
    male: "Male",
    female: "Female",
    nonBinary: "Non-Binary",
    transGender: "Trans-Gender",
    preferNotRespond: "Prefer not respond",


  },
  "ar": {
    patients: "المرضى",
    PATIENTS: "المرضى",
    welcome: "مرحبا بعودتك",
    dob: "تاريخ الولادة",
    DOB: "تاريخ الولادة",
    sex: "جنس",
    gender: "جنس",
    GENDER: "جنس",
    patientSummary: "ملخص المريض",
    noContent: "لا يوجد محتوى حتى الآن",
    age: "عمر",
    edit: "تعديل",
    back: "رجع",
    save: "حفظ",
    confirm: "تؤكد",
    cancel: "إلغاء",
    yes: "نعم",
    no: "لا",
    firstName: "الاسم المعطى",
    surname: "الكنية",
    country: "بلد",
    hometown: "مسقط رأس",
    selectDob: "اختر تاريخ الميلاد",
    phone: "هاتف",
    patientSearch: "البحث عن اسم المريض",
    search: "بحث",
    minAge: "الحد الإدنى للعمر",
    maxAge: "العمر الأقصى",
    advancedFilters: "مرشحات متقدمة ▼",
    hideFilters: "إخفاء المرشحات",
    clearFilters: "إعادة تعيين الفلاتر",
    newPatient: "مريض جديد",
    newVisit: "زيارة جديدة",
    newEntry: "دخول جديد",
    camp: "مخيم",
    vitals: "الأعضاء الحيوية",
    examination: "فحص",
    notes: "ملاحظات",
    complaint: "شكوى",
    treatment: "علاج او معاملة",
    diagnosis: "التشخيص",
    medicineDispensed: "الأدوية المستغلة",
    prescriptions: "وصفات",
    allergies: "الحساسية",
    medicalHistory: "تاريخ طبى",
    covidScreening: "COVID-19 فحص",
    enterTextHere: "أدخل النص هنا",
    visitDate: "موعد زيارة",
    visitHistory: "زيارة التاريخ",
    visitEvents: "زيارة الأحداث",
    visitType: "نوع الزيارة",
    trends: "اتجاهات",
    eventType: "نوع الحدث",
    datePrescribed: "التاريخ المحدد",
    provider: "طبيب",
    severity: "خطورة",
    onsetDate: "تاريخ البداية",
    departure: "مغادرة",
    to: "إلى",
    return: "إرجاع",
    fever: "حمى أم قشعريرة؟",
    dryCough: "سعال جاف؟",
    diffBreathing: "صعوبة في التنفس؟",
    soreThroat: "التهاب بالحلق أو سيلان  بالأنف؟",
    nausea: "غثيان، قيء، او إسهال؟",
    chestPain: "ألم في الصدر؟",
    confusion: "اضطراب إدراكي حديث؟",
    bluish: "الشفاه الزرقاء أم الوجه؟",
    fatigue: "إعياء؟",
    aches: "اوجاع والآم؟",
    headache: "صداع الراس؟",
    changeTasteSmell: "تغير في الطعم أو الرائحة؟",
    diabetes: "داء السكري؟",
    cardioDisease: "أمراض القلب والأوعية الدموية؟",
    pulmonaryDisease: "المرض الرئوي؟",
    renalDisease: "امراض الكلى؟",
    malignancy: "خباثة؟",
    pregnant: "حامل أو أسبوعين بعد الولادة؟",
    immunocompromised: "المنقوصي المناعة؟",
    exposureKnown: "مخالطة أفراد مصابين او مشتبهين بالإصابة بفيروس كوفيد-١٩؟",
    travel: "السفر خارج البلاد بالآونة الأخيرة؟",
    symptomsDate: "تاريخ ظهور الأعراض الأولى؟",
    riskFactors: "عوامل الخطر",
    hideRiskFactors: "إخفاء عوامل الخطر",
    testIsolate: "اختبار وعزل المريض",
    seekCare: "احصل على رعاية الطوارئ واعزل نفسك",
    noAction: "لا رد فعل",
    syncFailure: "فشل مزامنة قاعدة البيانات",
    syncFailureConnection: "تحقق من اتصال الإنترنت",
    syncFailureSystem: "اتصل بمسؤول النظام",
    syncSuccess: "نجاح مزامنة قاعدة البيانات",
    surgeryHx: "العمليات السابقة",
    chronicConditions: "الامراض المزمنة",
    currentMedications: "الأدوية الحالية",
    vaccinations: "التطعيمات ",
    generalObservations: "مراقبة عامة",
    covid19: "كوفيد-١٩",
    referral: "تحويل الى مختص",
    medicine: "طب",
    medication: "دواء",
    type: "نوع",
    tablet: "قرص",
    syrup: "شراب",
    ampule: "امبولة",
    suppository: "تحميلة",
    cream: "مرهم",
    drops: "قطرات",
    bottle: "زجاجة",
    spray: "رذاذ",
    gel: "جل",
    lotion: "غسول",
    dosage: "جرعة",
    days: "ايام",
    dentalTreatment: "العناية بالاسنان",
    physiotherapy: "العلاج الطبيعي",
    previousTreatment: "جلسات العلاج الطبيعي السابقة",
    findings: "نتائج الفحص",
    treatmentPlan: "خطة العلاج ",
    treatmentSession: "جلسة العلاج",
    recommendations: "توصيات",
    patientSnapshot: "صفحة المريض",
    logOut: "تسجيل خروج",
    sync: "مزامنة",
    // Mexico Clinic
    traumaType: "Trauma type",
    traumaDesc: "(DO NOT ask about this; only check mark if they self-volunteered the information)",
    traumaPhysical: "Physical",
    traumaSexual: "Sexual",
    traumaAbuse: "Witnessed abuse",
    traumaKilling: "Witnessed killing",
    traumaPSeperation: "Parental separation",
    traumaThreats: "Threats",
    traumaTJ: "Abuse in TJ",
    traumaOthers: "Others",
    // Mexico - Common Problems
    commonProblems: "Mental Health Common Problems",
    commonProblemsDesc: 'If there is tiem, fill out the questionnaire on the second page and mark the items that are applicable. If there is no time, it is not necessary to evaluate all the questions below nor the ones on the second page. Simply start by asking: “With what problems or stress that you’re currently having would you like help with?',
    commonProblemsHint: "Items that you must definitely check. Include the frequency when it is possible (ex. 2x/week)",
    difficultyEating: "Difficulty Eating",
    suicidalIdeation: "Suicidal Ideation",
    difficultySleeping: "Difficulty sleeping",
    hoursSlept: "Hours Slept",
    sleepingNight: "Nightmares",
    sleepingFalling: "Falling Asleep",
    sleepingWalking: "Waking Up middle of night",
    childrenSpecific: "Specific to Children",
    bedWetting: "Bed Wetting",
    defiant: "Defiant, fighting, or irritable",
    separationAnxiety: "Separation anxiety",
    communicationDifficulties: "Communication/learning difficulties",
    restless: "Restless",
    difficultyStoppingWorrying: "Difficulty stopping worrying",
    bodyAches: "Body Aches",
    bodyAchesWhere: "If so, where:",
    lowEnergy: "Low energy",
    noInterest: "No interest",
    guilt: "Guilt",
    hopeless: "Hopeless",
    flashbacks: "Flashbacks",
    hypervigilance: "Hypervigilance",
    sadIrritable: "Sad, cries often, or irritable",
    hallucinations: "Hallucinations (hears commands to kill/injure)",
    potentialDiagnosis: "Potential diagnosis",
    otherSymptom: "Other symptom/notes",
    // Interventions Used Form
    interventions: "Mental Health Interventions",
    resourceConnection: "Resource Connection",
    resourceConnectionSpecify: "Specify",
    activeListening: "Active Listening / Validation",
    psychoeducation: "Psychoeducation",
    sleepHygiene: "Sleep Hygiene",
    safeSpaceImagine: "Imagine a Safe Space",
    muscleRelaxation: "Progressive Muscle Relaxation",
    behavioralActivation: "Behavioral Activation",
    griefLetter: "Letter for Grief",
    changingThoughts: "Changing Thoughts",
    senses: "5 Senses",
    distractionTechniques: "Distraction Techniques",
    diaryYourself: "A Diary- praise yourself",
    chairTechnique: "Chair Technique",
    buildStrengths: "Build on Strengths/solutions",
    motivationalInterviewing: "Motivational Interviewing",
    diaphragmaticBreathing: "Diaphragmatic Breathing",
    safetyPlan: "Safety plan (note details; have migrant take picture of plan too)",
    interpersonalCommunication: "Interpersonal Communication",
    prayer: "Prayer (only if migrant self-reports already uses strategy)",
    supportivePeople: "Supportive people in their network",
    otherStrategies: "Other strategies used and safety/supervision plan details:",
    psychiatricMedications: "Psychiatric/Relevant Medications (Medicamentos):",
    // Mental Health
    mentalHealthFollowUp: "Mental health follow-up",
    inPerson: "In Person",
    tele: "Tele",
    femaleOnly: "Female Only",
    goClinic: "Go to Clinic",
    mentalOther: "Other",
    acupuncture: "Acupuncture (Wednesday and Thursday 9-1pm):",
    sendAudio: "Send Audios/Videos",
    psychiatry: "Psychiatry: First-time referral",
    refill: "Refill",
    takingRegularly: "Talking regularly",
    concernsFollowup: "Followup for concerns",
    lastFollowUpDate: "How long did the follow-up last:",
    firstSectionHint: "For people aged 12 or over, ask at the 1st session, 4th session and every 4 sessions after:",
    firstSectionQuestion: "Over the past 2 weeks, how often have you been bothered by the following problems:",
    notAtAll: "Not at all",
    severalDays: "Several days",
    moreHalfDays: "More than half the days",
    nearlyEveryDay: "Nearly every day",
    feelingNervous: "Feeling nervous, anxious, or on edge",
    noControlWorrying: "Not being able to stop or control worrying",
    littleInterest: "Little interest or pleasure in doing things",
    feelingDown: "Feeling down, depressed or hopeless",
    cantSleep: "I can't sleep or have nightmares",
    dontFeelSafeLiving: "I don't feel safe where I live (i.e., in my shelter or home; for people who live on the streets, you can ask if they know resources available to them)",
    firstSectionScore: "Total score (sum of four questions):",
    // Mental Section2
    secondSectionQuestion: "From the statements below, please mark or circle the answer that best describes how you feel. Do you feel that:",
    dealWithAny: "Is able to deal (cope) with anything",
    dealWithMostThings: "Is able to deal (cope) with most things ",
    dealWithSomeThings: "Is able to deal (cope) with some things, but cannot deal with other things",
    cannotDealWithMost: "Can't deal with most things",
    cannotDealWithAny: "Can't deal with anything",
    // Mental Section3
    thirdSectionHint: "For parents of children aged 11 or under, ask at the 1st session, 4th session and every 4 sessions after:",
    thridSectionQuestion: "How often did each of these happen in the last 30 days?",
    frequent1: "Never/Rarely",
    frequent2: "1-2 times per month",
    frequent3: "1-2 times per week",
    frequent4: "+3 times per week",
    childBodyFeeling: "Your child has strong feelings in their body when they remember something that happened (sweating, heart beats fast, feel sick).",
    childAwayFromPeople: "Your child tries to stay away from people, places, or things that remind them about something that happened.",
    childFeelingHappy: "Your child has trouble feeling happy.",
    childTroubleSleeping: "Your child has trouble sleeping.",
    childHardPayAttention: "It's hard for your child to concentrate or pay attention.",
    childFeelsAlone: "Your child feels alone and not close to people around them.",
    forthSectionHint: " For children aged 11 or under, ask at the 1st session, 4th session and every 4 sessions after:",
    forthSectionQuestion: "How often did each of these happen in the last 30 days?",
    bodyFeelings: "Strong feelings in your body when you remember something that happened (sweating, heart beats fast, feel sick).",
    awayFromPeople: "Try to stay away from people, places, or things that remind you about something that happened.",
    feelingHappy: "Trouble feeling happy.",
    troubleSleeping: "Trouble sleeping.",
    hardPayAttention: "Hard to concentrate or pay attention.",
    feelAlone: "Feel alone and not close to people around you.",
    pastWeekStress: "Circle the number (0-10) that describes how much stress you have been feeling this past week, including today:",
    none: "None",
    little: "A little",
    moderately: "Moderately",
    goodDeal: "A Good Deal",
    alot: "A lot (The Worse)",

    // Vitals
    respiratoryRate: "Respiratory Rate",
    bloodGlucose: "Blood Glucose",
    weight: "Weight",
    pulse: "Pulse",

    // Medicine
    route: "Route",
    oral: "Oral",
    topical: "Topical",
    subcutaneous: "Subcutaneous",
    intramuscular: "Intramuscular",
    deepIntramuscular: "Deep Intramuscular",

    // Physical Exam
    hpi: "HPI",
    examinationFindings: "Ros/Examination findings",
    appearance: "Appearance",
    eent: "EENT",
    heartPulses: "Heart, pulses",
    lungs: "Lungs",
    abdomen: "Abdomen",
    genitales: "Genitales",
    extremities: "Extremities",
    skin: "Skin",
    neuro: "Neuro",
    isPregnant: "Pregnant",
    lastPeriodFirstDay: "First day of last period?",
    assessmentPlan: "Assessment and Plan",
    unsure: "Unsure",

    // Medical History
    tobacco: "Tobacco",
    alcohol: "Alcohol",
    drugs: "Drugs",
    familyHistory: "Family History",
    diseasesConditions: "Diseases/Conditions",
    medicalHistoryDetails: "What relatives? dates? Treatment / Other?",
    cancer: "Cancer",
    epilepsy: "Epilepsy or other Seizures",
    heartDisease: "Heart Disease",
    hypertension: "Hypertension",
    thyroidConditions: "Thyroid Conditions",
    tuberculosis: "Tuberculosis",
    // diabetes: "Diabetes",
    multipleBirths: "Multiple Births (Twins)",
    breechBirths: "Breech Births",
    spiritualEmotionalHistory: "Spiritual Emotional History",
    spiritualEmotionalHistoryDetails: "What relatives (direct or distant)? dates? Treatment / Other?",
    conditions: "Conditions",
    domesticViolence: "Domestic Violence",
    alcoholismDrugAddiction: "Alcoholism / Drug Addiction",
    codependency: "Codependency",
    nutritionalDisorder: "Nutritional Disorder",
    abuse: "Abuse",
    sexualAbuse: "sexual abuse",
    mentalDisorders: "Mental disorders",
    showMore: "Show more medicines:",

    // Nursing notes
    nursingNotes: "Nursing Notes",
    bodyHabitus: "Body Habitus",
    procedures: "Procedures",
    observations: "Observations",

    // Lab
    bloodTestImaging: "Blood Test and Imaging",
    date: "Date",
    test: "Test",
    normal: "Normal",
    abnormal: "Abnormal",
    labNotes: "Notes",
    bloodTest: "Blood Test",
    imaging: "Imaging",
    typeOfImaging: "Type of imaging",
    result: "Result",

    // Gender
    male: "Male",
    female: "Female",
    nonBinary: "Non-Binary",
    transGender: "Trans-Gender",
    preferNotRespond: "Prefer not respond",
  },
  "sp": {
    patients: "Pacientes",
    PATIENTS: "PACIENTES",
    welcome: "Bienvenido de vuelta",
    dob: "Fecha de nacimiento ",
    DOB: "Fecha de nacimiento ",
    sex: "Sexo",
    gender: "Género",
    GENDER: "GENERO",
    patientSummary: "Resumen del paciente",
    noContent: "No hay contenido aún",
    age: "EDAD",
    edit: "EDITAR",
    back: "< Volver a atrás",
    save: "GUARDAR",
    confirm: "CONFIRMAR",
    cancel: "CANCELAR",
    yes: "Sí",
    no: "No",
    firstName: "Nombre",
    surname: "Apellido",
    country: "País",
    hometown: "Ciudad de origen",
    selectDob: "Seleccione fecha de nacimiento",
    phone: "Teléfono",
    patientSearch: "Buscar nombre del paciente...",
    search: "Buscar",
    minAge: "Edad Mínima",
    maxAge: "Edad Máxima",
    advancedFilters: "Filtros Avanzados ▼",
    hideFilters: "Ocultar Filtros",
    clearFilters: "Restablecer Filtros",
    newPatient: "New Patient",
    newVisit: "New Visit",
    newEntry: "New Entry",
    // camp: "Nombre del campo de refugiados",
    camp: "direccion",
    vitals: "Signos vitales",
    examination: "Examen físico",
    notes: "Notas",
    complaint: "Problema primario",
    treatment: "Tratamiento",
    diagnosis: "Diagnóstico",
    medicineDispensed: "Medicamento suscrito",
    prescriptions: "Recetas de medicamentos",
    allergies: "Alergias",
    medicalHistory: "Historial médico",
    covidScreening: "Prueba de COVID-19",
    enterTextHere: "Introduzca texto aquí",
    visitDate: "Fecha de la visita",
    visitHistory: "Historia de la visita",
    visitEvents: "Eventos durante la visita",
    visitType: "Tipo de visita",
    trends: "Tendencias",
    eventType: "Tipo de evento",
    datePrescribed: "Fecha de prescripción",
    provider: "Proveedor médico",
    severity: "Severidad",
    onsetDate: "Fecha de comienzo de los síntomas",
    departure: "Ida",
    to: "a ",
    return: "Vuelta",
    fever: "¿Fiebre o escalofríos?",
    dryCough: "¿Tos seca?",
    diffBreathing: "¿Dificultad al respirar?",
    soreThroat: "¿Dolor de garganta o secreción nasal?",
    nausea: "¿Náuseas, vómitos o diarrea?",
    chestPain: "¿Dolor de pecho?",
    confusion: "¿Nueva confusión?",
    bluish: "¿Labios azulados/ violetas?",
    fatigue: "¿Fatiga?",
    aches: "¿Dolores y molestias?",
    headache: "¿Dolor de cabeza?",
    changeTasteSmell: "¿Cambio de gusto u olfato?",
    diabetes: "Diabetes?",
    cardioDisease: "¿Problemas del corazón?",
    pulmonaryDisease: "¿Enfermedad en los pulmones?",
    renalDisease: "¿Enfermedad de los riñones?",
    malignancy: "¿Cáncer?",
    pregnant: "Mujer recién dada a luz?",
    immunocompromised: "¿Inmunocomprometido? / ¿Tiene las defensas bajas?",
    exposureKnown: "¿Contacto reciente con personas con COVID-19 conocido o sospechado?",
    travel: "¿Viaje reciente fuera del país?",
    symptomsDate: "¿Fecha de aparición de los primeros síntomas?",
    riskFactors: "Factores de riesgo",
    hideRiskFactors: "Ocultar factores de riesgo",
    testIsolate: "Hacerle la prueba/Aislar al paciente",
    seekCare: "Busque atención de emergencia y aísle",
    noAction: "No es necesario tomar ninguna acción",
    syncFailure: "¡Fallo de sincronización!",
    syncFailureConnection: "Verifica la conexión a internet",
    syncFailureSystem: "Comuníquese con el administrador del sistema",
    syncSuccess: "Éxito en la sincronización",
    surgeryHx: "Cirugías",
    chronicConditions: "Condiciones cronicas",
    currentMedications: "Medicamentos",
    vaccinations: "Vacunas",
    generalObservations: "General Observations",
    covid19: "COVID-19",
    referral: "Especialista",
    medicine: "Medicine",
    medication: "Medicamento",
    type: "Tipo",
    tablet: "Tableta",
    syrup: "Jarabe",
    ampule: "Ampolla",
    suppository: "Supositorio",
    cream: "Crema",
    drops: "Gotas",
    bottle: "Botella",
    spray: "Rociar",
    gel: "Gel",
    lotion: "Loción",
    dosage: "Dosis",
    days: "Días",
    dentalTreatment: "Tratamiento dental",
    physiotherapy: "Examen Físico",
    previousTreatment: "Previous Physio Treatment",
    findings: "Examination Findings",
    treatmentPlan: "Treatment Plan",
    treatmentSession: "Treatment Session",
    recommendations: "Recomendaciones",
    patientSnapshot: "Patient Snapshot",
    logOut: "Log Out",
    sync: "Sync",
    // Mexico Clinic
    traumaType: "Categoría de Trauma",
    traumaDesc: "(NO preguntes sobre esto; solo marque si ofrecen información voluntariamente):",
    traumaPhysical: "físical",
    traumaSexual: "Sexual",
    traumaAbuse: "Testigo de abuso",
    traumaKilling: "Presenció un asesinato",
    traumaPSeperation: "Separación de sus padres",
    traumaThreats: "Threats",
    traumaTJ: "Abuse in TJ",
    traumaOthers: "Otro",
    // Mexico - Common Problems
    commonProblems: "Salud Mental Problemas Comunes",
    commonProblemsDesc: 'Si tienes tiempo, llena el cuestionario en la segunda página y marca las cosas que aplican abajo. Si no tienes tiempo, no es necesario que los evalúe todas las preguntas abajo ni los en la segunda página. Simplemente comience con: "¿Con cuáles problemas o estrés que tiene actualmente, le gustaría recibir ayuda?',
    commonProblemsHint: "Cosas que definitivamente chequear. Incluye frecuencia cuando es posible (p.ej. 2x/semana)",
    difficultyEating: "*Dificultad para comer",
    suicidalIdeation: "*Ideaciones del suicidio*",
    difficultySleeping: "*Dificultad para dormir",
    hoursSlept: "Horas de sueño:",
    sleepingNight: "Pesadillas",
    sleepingFalling: "Dificultad para conciliar el sueño",
    sleepingWalking: "Despertar del sueño",
    restless: "Inquieto",
    difficultyStoppingWorrying: "Dificultad para dejar de preocuparse",
    bodyAches: "Dolor de cuerpo",
    bodyAchesWhere: "En donde:",
    lowEnergy: "Energía baja",
    noInterest: "Falta de interés",
    guilt: "Culpa",
    hopeless: "Sin esperanza",
    flashbacks: "Recuerdos",
    hypervigilance: "Hipervigilancia",
    sadIrritable: "Triste, llora con frecuencia o irritable",
    hallucinations: "Alucinación (nota oír órdenes de matar/herir) Potencial diagnosis:",
    potentialDiagnosis: "Potential diagnosis",
    otherSymptom: "Otros síntomas/notas:",
    childrenSpecific: "Específica para niños",
    bedWetting: "Mojar la cama",
    defiant: "Desafiante, luchador o irritable",
    separationAnxiety: "Ansiedad de separación",
    communicationDifficulties: "Dificultades de comunicación / aprendizaje:",
    // Interventions Used Form
    interventions: "Intervenciones Salud Mental",
    resourceConnection: "Conectar con otras recursos",
    resourceConnectionSpecify: "Especifique",
    activeListening: "Escucha activa / validación",
    psychoeducation: "Psicoeducación",
    sleepHygiene: "Higiene del sueño",
    safeSpaceImagine: "Imaginar un lugar seguro",
    muscleRelaxation: "Relajación muscular progresiva",
    behavioralActivation: "Activación conductual",
    griefLetter: "Carta de duelo",
    changingThoughts: "Cambiar pensamientos",
    senses: "5 Sentidos",
    distractionTechniques: "Técnicas de distracción",
    diaryYourself: "A DIARIO – elogiar",
    chairTechnique: "Técnica de la silla",
    buildStrengths: "Construir sobre fortalezas / soluciones",
    motivationalInterviewing: "Entrevista motivacional",
    diaphragmaticBreathing: "Respiración diafragmática",
    safetyPlan: "Plan de seguridad (anotar los detalles; hacer que el paciente tome una foto del plan también)",
    interpersonalCommunication: "Comunicación interpersonal",
    prayer: "Oración, solo si los autoinformes de los migrantes ya utilizan la estrategia",
    supportivePeople: "Las personas de apoyo en su red:",
    otherStrategies: "*Otras estrategias utilizadas y detalles del plan de seguridad/supervisión:",
    psychiatricMedications: "Medicamentos psiquiátricos/relevantes:",
    // Mental Health Follow up
    mentalHealthFollowUp: "Seguimiento:",
    inPerson: "En persona",
    tele: "Tele",
    femaleOnly: "Sólo mujer",
    goClinic: "Ir a la clínica",
    mentalOther: "Otro:",
    acupuncture: "Acupuncture (Wednesday and Thursday 9-1pm):",
    sendAudio: "Enviar audios/vídeos:",
    psychiatry: "Psiquiatría: Derivación por 1º  vez",
    refill: "Resurtido",
    takingRegularly: "Está Tomando regularmente?",
    concernsFollowup: "Seguimiento de inquietudes",
    lastFollowUpDate: "¿Cuánto tiempo duró el seguimiento?:",
    firstSectionHint: "Para gente con 12 años o más pregunta las de 1º sesión, 4º sesión y cada 4 sesión después:",
    firstSectionQuestion: "Durante las últimas 2 semanas, ¿con qué frecuencia lo(a) han molestado los siguientes problemas:",
    notAtAll: "Nunca",
    severalDays: "Varios días",
    moreHalfDays: "Más de la mitad de los días",
    nearlyEveryDay: "Casi todos los días",
    feelingNervous: "Sentirse nervioso/ansioso, intranquilo o con los nervios de punta",
    noControlWorrying: "No poder dejar de preocuparse o no poder controlar la preocupación",
    littleInterest: "Poco interés o placer en hacer cosas",
    FeelingDown: "Sentirse desanimado(a)/decaído, deprimido(a) o sin esperanza",
    cantSleep: "No puedo dormir o tener pesadillas.",
    dontFeelSafeLiving: "No me siento seguro donde que vivo ahora (p.ej. en mi albergue o casa; para gente que viven el calle, puedes chequear si conocen los recursos que para ellos).",
    firstSectionScore: "Suma:",
    // Mental Section2
    secondSectionQuestion: "De las oraciones a continuación, marque o circule la respuesta que mejor describa cómo se siente. Usted siente que:",
    dealWithAny: "Es capaz de lidiar (hacerle frente) con cualquier cosa",
    dealWithMostThings: "Es capaz de lidiar (hacerle frente) con la mayoría de las cosas",
    dealWithSomeThings: "Es capaz de lidiar (hacerle frente) con algunas cosas, pero no puede hacerles frente a otras cosas",
    cannotDealWithMost: "No puede lidiar con la mayoría de las cosas",
    cannotDealWithAny: "No puede lidiar con nada",
    // Mental Section3
    thirdSectionHint: "Para Los Padres de Niños 11 Años o Menos pregunta las de 1º sesión, 4º sesión y cada 4 sesión después:",
    thridSectionQuestion: "Con qué frecuencia le sucedieron cada una de las siguientes cosas en los últimos 30 días?",
    frequent1: "Nunca/Raramente",
    frequent2: "1-2 veces al mes",
    frequent3: "1-2 veces por semana",
    frequent4: "+3 veces por semana",
    childBodyFeeling: "Siente fuertes sensaciones en su cuerpo cuando recuerda algo que sucedió (sudoración, latidos rápidos del corazón, sentirse enfermo)",
    childAwayFromPeople: "Intenta evitar personas, lugares o cosas que le hacen recordar algo que sucedió.",
    childFeelingHappy: "Le cuesta trabajo sentirse feliz.",
    childTroubleSleeping: "Le cuesta trabajo dormir.",
    childHardPayAttention: "Le es difícil concentrarse o prestar atención.",
    childFeelsAlone: "Se siente solo/a y alejado/a de las personas a su alrededor.",
    forthSectionHint: "Para Los Niños 11 Años o Menos pregunta las de 1º sesión, 4º sesión y cada 4 sesión después:",
    forthSectionQuestion: "Con qué frecuencia te sucedieron cada una de las siguientes cosas en los últimos 30 días?",
    bodyFeelings: "Fuertes sensaciones en tu cuerpo cuando recuerdas algo que sucedió (sudoración, latidos rápidos del corazón, sentirs enfermo)",
    awayFromPeople: "Intentas evitar personas, lugares o cosas que te hacen recordar algo que sucedió.",
    feelingHappy: "Te cuesta trabajo sentirte feliz.",
    troubleSleeping: "Te cuesta trabajo dormir.",
    hardPayAttention: "Te es difícil concentrarte o prestar atención.",
    feelAlone: "Te sientes solo/a y alejado/a de las personas a tu alrededor.",
    pastWeekStress: "Encierre en un círculo el número (del 0 al 10) que mejor describa cuánta angustia ha estado sintiendo esta última semana, incluyendo el día de hoy:",
    none: "Nada",
    little: "Un Poquito",
    moderately: "Moderadamente",
    goodDeal: "Bastante",
    alot: "Muchísimo (El Peor)",

    // Vitals
    respiratoryRate: "frecuencia respiratoria",
    bloodGlucose: "Blood Glucosa",
    weight: "Peso",
    pulse: "Pulso",

    
    // Medicine
    route: "Via de administracion",
    oral: "Via oral",
    topical: "Topical",
    subcutaneous: "Subcutanea",
    intramuscular: "Intramuscular",
    deepIntramuscular: "Intramuscular Profunda",

    // Physical Exam
    hpi: "Historia de la enfermedad",
    examinationFindings: "Examen físico normal",
    appearance: "Apariencia",
    eent: "Ojos, oídos, nariz, garganta",
    heartPulses: "Corazón, pulsos",
    lungs: "Pulmones",
    abdomen: "Abdomen",
    genitales: "Genitales",
    extremities: "Extremidades",
    skin: "Piel",
    neuro: "Neuro",
    isPregnant: "¿Está embarazada",
    lastPeriodFirstDay: "Cuál fue el primer día de su última regla?",
    assessmentPlan: "Plan de Cuidado",
    unsure: "No sé ",

    // Medical History
    tobacco: "Tabaco",
    alcohol: "Cerveza",
    drugs: "Droga",
    familyHistory: "Antecedentes Heredofamiliares",
    diseasesConditions: "Enfermedades/Condiciones",
    medicalHistoryDetails: "Que Familiares? Fechas? Tratamiento / Otros?",
    cancer: "Cáncer",
    epilepsy: "Epilepsia u otras Convulsiones",
    heartDisease: "Cardiacas",
    hypertension: "Hipertension",
    thyroidConditions: "Tiroides",
    tuberculosis: "Tuberculosis",
    // diabetes: "Diabetes",
    multipleBirths: "Gemelos",
    breechBirths: "Pelvicos",
    spiritualEmotionalHistory: "Historia Espiritual Emocional ",
    spiritualEmotionalHistoryDetails: "Que Familiares(directo o lejano)? Fechas? Tratamiento / Otros?",
    conditions: "Condiciones",
    domesticViolence: "Violencia intrafamiliar",
    alcoholismDrugAddiction: "Alcoholismo / Drogadicción",
    codependency: "Codependencias",
    nutritionalDisorder: "Desorden nutricional",
    abuse: "Abuso",
    sexualAbuse: "Abuso sexual",
    mentalDisorders: "Desórdenes Mentales",
    showMore: "Agregar más medicamentos",

    // Nursing notes
    nursingNotes: "Nota de enfermería",
    bodyHabitus: "Habitus exterior",
    procedures: "Procedimientos realizados",
    observations: "Observaciones",

    // Lab
    bloodTestImaging: "Pruebas de Sangre y Radiografia",
    date: "Fecha",
    test: "Prueba",
    normal: "Normal",
    abnormal: "Anormal",
    labNotes: "Notas sobre los resultados",
    bloodTest: "Pruebas de Sangre",
    imaging: "Radiología",
    typeOfImaging: "Tipo de Estudio",
    result: "Resultado",

    // Gender
    male: "Hombre",
    female: "Mujer",
    nonBinary: "No Binario",
    transGender: "Transgénero",
    preferNotRespond: "Prefiere no identificar",

  }
};